apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: appservices.gramola.redhat.com
spec:
  group: gramola.redhat.com
  names:
    kind: AppService
    listKind: AppServiceList
    plural: appservices
    singular: appservice
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: AppService is the Schema for the appservices API defines Gramola
        Backend Services
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AppServiceSpec defines the desired state of AppService
          properties:
            alias:
              description: Different names for Gramola Service
              enum:
              - Gramola
              - Gramophone
              - Phonograph
              type: string
            enabled:
              description: Flags if the the AppService object is enabled or not
              type: boolean
            initialized:
              description: Flags if the object has been initialized or not
              type: boolean
          required:
          - enabled
          type: object
        status:
          description: AppServiceStatus defines the observed state of AppService
          properties:
            conditions:
              description: Status Conditions
              items:
                description: AppServiceCondition defines the desired state
                properties:
                  lastTransitionTime:
                    description: The last time the condition transitioned from one
                      status to another.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    enum:
                    - Initialized
                    - Waiting
                    - Progressing
                    - Finalising
                    - Succeeded
                    - Failed
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    enum:
                    - "True"
                    - "False"
                    - Unknown
                    type: string
                  type:
                    description: Type of replication controller condition.
                    enum:
                    - Promoted
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            eventsDatabaseScriptRuns:
              description: List of Event Database Scripts Runs
              items:
                description: DatabaseScriptRun logs script run and status
                properties:
                  eventsDatabaseUpdated:
                    description: Status of the run of the Script
                    enum:
                    - Succeeded
                    - Failed
                    - Unknown
                    type: string
                  script:
                    description: Script
                    type: string
                required:
                - script
                type: object
              type: array
            eventsDatabaseUpdated:
              description: Indicates if the Events Database has been updated or not
              enum:
              - BackupStarted
              - RequeueEvent
              - NoAction
              type: string
            lastAction:
              description: Last Action run
              enum:
              - Unknown
              - Succeeded
              - Failed
              type: string
            lastUpdate:
              description: LastUpdate records the last time an update was regitered
              format: date-time
              type: string
            reason:
              description: Reason for the update or change in status
              type: string
            status:
              description: Status shows the reconcile run
              enum:
              - Succeded
              - Progressing
              - Failed
              - "True"
              type: string
          required:
          - lastAction
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
