scorecard:
    # Setting a global scorecard option
    output: json
    plugins:
      # `basic` tests configured to test 2 CRs
      - basic:
          cr-manifest:
            - "deploy/crds/gramola.redhat.com_appservices_crd.yaml"
            - "deploy/crds/gramola.redhat.com_v1alpha1_appservice_cr.yaml"
      # `olm` tests configured to test 2 CRs
      - olm:
          cr-manifest:
            - "deploy/crds/gramola.redhat.com_v1alpha1_appservice_cr.yaml"
          csv-path: "deploy/olm-catalog/gramola-operator/0.0.1/gramola-operator.v0.0.1.clusterserviceversion.yaml"