apiVersion: apps/v1
kind: Deployment
metadata:
  name: gramola-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gramola-operator
  template:
    metadata:
      labels:
        name: gramola-operator
    spec:
      serviceAccountName: gramola-operator
      containers:
        - name: gramola-operator
          # Replace this with the built image name
          image: quay.io/cvicensa/gramola-operator:v0.1.0
          command:
          - gramola-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "gramola-operator"
