apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "gramola.redhat.com/v1alpha1",
          "kind": "AppService",
          "metadata": {
            "name": "gramola"
          },
          "spec": {
            "enabled": true
          }
        }
      ]
    capabilities: Basic Install
    categories: Other
    certified: "false"
    containerImage: quay.io/cvicensa/gramola-operator:0.0.1
    createdAt: "2020-03-12T02:45:00Z"
    description: Gramola Operator deploys the backend needed to support Gramola mobile
      App.
    repository: https://github.com/cvicens/gramola-operator
    support: ACME
  name: gramola-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AppService is the Schema for the appservices API defines Gramola
        Backend Services
      displayName: AppService
      kind: AppService
      name: appservices.gramola.redhat.com
      specDescriptors:
      - description: Different names for Gramola Service
        displayName: Alias
        path: alias
      - description: Flags if the the AppService object is enabled or not
        displayName: Enabled
        path: enabled
      version: v1alpha1
  description: |
    A sample social event management system (**Gramola**) built mostly with [Quarkus](https://quarkus.io).

    [Gramola](https://en.wikipedia.org/wiki/Gramola) is a kind of gramophone or jukebox.

    ### This is just a sample operator

    This operator deploys an application made of several microservices. The code of the application is [here](https://github.com/cvicens/gramola). The code of the operator is [here](https://github.com/cvicens/gramola-operator)

    ### Supported Features

    **Updates via automated operations**
    New versions are deployed using a rolling update with no downtime, making it easy to stay up to date.
  displayName: Gramola Operator
  icon:
  - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iaXNvLTg4NTktMSI/Pg0KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDE5LjAuMCwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPg0KPHN2ZyB2ZXJzaW9uPSIxLjEiIGlkPSJMYXllcl8xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB4PSIwcHgiIHk9IjBweCINCgkgdmlld0JveD0iMCAwIDQ5Ni4yIDQ5Ni4yIiBzdHlsZT0iZW5hYmxlLWJhY2tncm91bmQ6bmV3IDAgMCA0OTYuMiA0OTYuMjsiIHhtbDpzcGFjZT0icHJlc2VydmUiPg0KPHBhdGggc3R5bGU9ImZpbGw6I0ZBQkMzRDsiIGQ9Ik00OTYuMiwyNDguMUM0OTYuMiwxMTEuMSwzODUuMSwwLDI0OC4xLDBTMCwxMTEuMSwwLDI0OC4xczExMS4xLDI0OC4xLDI0OC4xLDI0OC4xDQoJUzQ5Ni4yLDM4NS4xLDQ5Ni4yLDI0OC4xeiIvPg0KPHBhdGggc3R5bGU9ImZpbGw6IzI5MjkyOTsiIGQ9Ik0zNDEuMiwzMTguNWMwLDAsMTEuNi0xMC43LDEwLjgtNDkuNWMwLDAsMC4zLTI2LjYsNS4zLTI5LjFjNi42LTMuMiwxNy4xLDAuNiwxNC4xLDkuMw0KCWMtMC42LDEuNi00LjYsMy44LTYuOC0wLjhjMCwwLTMtMy0zLDIuM2MwLDAsNyw1OS4zLTIuOSw3OC40TDM0MS4yLDMxOC41eiIvPg0KPHBvbHlnb24gc3R5bGU9ImZpbGw6IzY2M0QyNjsiIHBvaW50cz0iNDA1LjcsMzkxLjcgMzg2LjIsMzcwLjUgMjgzLDM0NC4zIDE3OS43LDM3MC41IDE2MC4yLDM5MS43IDI4Mi45LDQzNi4zIDI4Myw0MzYuMiANCgkyODMsNDM2LjMgIi8+DQo8cG9seWdvbiBzdHlsZT0iZmlsbDojODI0ODMxOyIgcG9pbnRzPSIyODMsMzQ0LjMgMTc5LjcsMzcwLjUgMjgzLDQwOC4xIDM4Ni4yLDM3MC41ICIvPg0KPHBvbHlnb24gc3R5bGU9ImZpbGw6IzUxMkUxRDsiIHBvaW50cz0iNDA1LjcsMzkxLjcgMjgzLDQzNi4zIDI4Myw0MDguMSAzODYuMiwzNzAuNSAiLz4NCjxwb2x5Z29uIHN0eWxlPSJmaWxsOiM2QjNCMjg7IiBwb2ludHM9IjE2MC4yLDM5MS43IDI4Mi45LDQzNi4zIDI4Mi45LDQwOC4xIDE3OS43LDM3MC41ICIvPg0KPHBvbHlnb24gc3R5bGU9ImZpbGw6IzY2M0QyNjsiIHBvaW50cz0iMzg2LjEsMzcwLjQgMzg1LjksMzMyLjkgMjgzLDI5NS40IDE4MCwzMzIuOSAxNzkuOCwzNzAuNCAyODIuOSw0MDcuOSAyODMsNDA3LjggMjgzLDQwNy45IA0KCSIvPg0KPHBvbHlnb24gc3R5bGU9ImZpbGw6IzgyNDgzMTsiIHBvaW50cz0iMjgzLDI5NS40IDE4MCwzMzIuOSAyODMsMzcwLjQgMzg1LjksMzMyLjkgIi8+DQo8cG9seWdvbiBzdHlsZT0iZmlsbDojNjYzRDI2OyIgcG9pbnRzPSIzODYuMSwzNzAuNCAyODMsNDA3LjkgMjgzLDM3MC40IDM4NS45LDMzMi45ICIvPg0KPHBvbHlnb24gc3R5bGU9ImZpbGw6Izc3NDQyQjsiIHBvaW50cz0iMTc5LjgsMzcwLjQgMjgyLjksNDA3LjkgMjgyLjksMzcwLjQgMTgwLDMzMi45ICIvPg0KPGVsbGlwc2Ugc3R5bGU9ImZpbGw6IzJEMTkxMjsiIGN4PSIzMzcuMSIgY3k9IjM2MS41IiByeD0iNS4xIiByeT0iNS44Ii8+DQo8cGF0aCBzdHlsZT0iZmlsbDojRDRENEQ0OyIgZD0iTTM2Ny4zLDM5Ny42YzAsMC0xMC4xLTMuNS0xMC44LTMuOGMtMS4zLTAuNS0yLjItMS44LTIuMy0zLjNjLTAuMS0xLjEsMC0yMSwwLTIyLjINCgljMC0xLjMtMC42LTMuNC0yLjMtNC4yYy0yLjEtMC45LTE0LjgtNS4yLTE0LjgtNS4yYy0xLjEtMC40LTIuMywwLjItMi43LDEuM2MtMC40LDEuMSwwLjIsMi4zLDEuMywyLjdjMCwwLDEwLjEsMy41LDEwLjgsMy44DQoJYzEuMywwLjUsMi4yLDEuOCwyLjMsMy4zYzAuMSwxLjEsMCwyMSwwLDIyLjJjMCwxLjMsMC42LDMuNCwyLjMsNC4yYzIuMSwwLjksMTQuOCw1LjIsMTQuOCw1LjJjMS4xLDAuNCwyLjMtMC4yLDIuNy0xLjMNCglDMzY5LDM5OS4yLDM2OC40LDM5OCwzNjcuMywzOTcuNnoiLz4NCjxwYXRoIHN0eWxlPSJmaWxsOiMxNjE2MTY7IiBkPSJNMzY4LjMsMzk1LjljMCwwLTgtMy05LjEtMy40Yy0yLTAuOC0zLjQtMi43LTMuNi01LjFsLTguMiwwLjhjLTAuMywxLDAsMS43LDAsMmMwLDIsMC45LDUuMiwzLjUsNi40DQoJYzMuMywxLjQsMTUuMiw1LjYsMTUuMiw1LjZjMS43LDAuNiwzLjYtMC4zLDQuMi0yQzM3MC45LDM5OC40LDM3MCwzOTYuNSwzNjguMywzOTUuOXoiLz4NCjxlbGxpcHNlIHN0eWxlPSJmaWxsOiMxMzM4Mjk7IiBjeD0iMjgyLjQiIGN5PSIzMzEuOCIgcng9IjU5LjciIHJ5PSIyNC4zIi8+DQo8ZWxsaXBzZSBzdHlsZT0iZmlsbDojMUY2MDQ4OyIgY3g9IjI4Mi40IiBjeT0iMzI2LjciIHJ4PSI1OS43IiByeT0iMjQuMyIvPg0KPGVsbGlwc2Ugc3R5bGU9ImZpbGw6IzBGMzAyMzsiIGN4PSIyODIuNCIgY3k9IjMyNi43IiByeD0iMi44IiByeT0iMS44Ii8+DQo8cGF0aCBzdHlsZT0iZmlsbDojQTU5MDZGOyIgZD0iTTMzNy4xLDIyNi41bC02OS41LTMyYy0zNi41LTE2LjItNjMuNC03Ny4xLTYzLjQtNzcuMUwxNjMuNiwyNjNjODIuMi01NC4zLDE3Ni4zLTEzLjksMTc2LjMtMTMuOQ0KCXMyLjMsMi44LDEuMywxOC40cy0xMS40LDE2LjQtMTEuNCwxNi40bC0zMy42LDcuNWw0LjksNi4ybDI4LjktNS43YzcuMi0xLjMsMTItNS4zLDEyLTUuM2MxMS41LTEwLjQsMTAuNy0zMiwxMC43LTMyDQoJQzM1Mi43LDIzMy4yLDMzNy4xLDIyNi41LDMzNy4xLDIyNi41eiIvPg0KPHBhdGggc3R5bGU9ImZpbGw6IzkyN0U1OTsiIGQ9Ik0xNDIuNiw3OS45YzAsMC0xNiwwLjgtMjcuNCw1MC4yYzAsMC0xOC41LDIxLjMtMTguNSw2MS45YzAsMC0xNC43LDQ0LjEtNC42LDYzLjQNCgljMCwwLTguMSwzOS4xLDEwLjcsNDAuNmMwLDAsNi42LDI5LjksMjkuNCwwLjVjMCwwLDI0LjksMCwzOC42LTUzLjhjMCwwLDI1LjQtMzcuNSwyNi45LTg4LjNjMCwwLDE2LjctNTQuOCwwLTc1LjENCgljMCwwLDEuNS00My4xLTIyLjgtMjcuNEMxNzQuOCw1MiwxNTcuNSwzNy44LDE0Mi42LDc5Ljl6Ii8+DQo8cGF0aCBzdHlsZT0iZmlsbDojNzI2MDQ0OyIgZD0iTTE0My40LDk5LjhjMCwwLTEyLjgsMC42LTIxLjksNDAuMmMwLDAtMTQuOCwxNy0xNC44LDQ5LjVjMCwwLTExLjgsMzUuMy0zLjcsNTAuNw0KCWMwLDAtNi41LDMxLjIsOC41LDMyLjVjMCwwLDUuMywyMy45LDIzLjUsMC40YzAsMCwxOS45LDAsMzAuOC00M2MwLDAsMjAuMy0zMCwyMS41LTcwLjZjMCwwLDEzLjQtNDMuOCwwLTYwYzAsMCwxLjItMzQuNS0xOC4zLTIxLjkNCglDMTY5LjIsNzcuNSwxNTUuNCw2Ni4xLDE0My40LDk5Ljh6Ii8+DQo8cG9seWdvbiBzdHlsZT0iZmlsbDojMjkyOTI5OyIgcG9pbnRzPSIyODUuOCwzMTEuOSAyODkuNCwzMjMuNCAyOTIuOSwzMTEuNCAiLz4NCjxnPg0KCQ0KCQk8ZWxsaXBzZSB0cmFuc2Zvcm09Im1hdHJpeCgtMC4yNTU0IDAuOTY2OCAtMC45NjY4IC0wLjI1NTQgNjQ5LjIwNzIgOTkuODA4MykiIHN0eWxlPSJmaWxsOiM4RTc5NUU7IiBjeD0iMjg2LjE3MSIgY3k9IjI5OS44OTMiIHJ4PSIxMi43IiByeT0iMTIiLz4NCgkNCgkJPHJlY3QgeD0iMjg2LjA4NiIgeT0iMjg3LjQ4MyIgdHJhbnNmb3JtPSJtYXRyaXgoLTAuOTY2OCAtMC4yNTU0IDAuMjU1NCAtMC45NjY4IDQ4OS4wNTA0IDY2My45NzI4KSIgc3R5bGU9ImZpbGw6IzhFNzk1RTsiIHdpZHRoPSIzLjEiIGhlaWdodD0iMjUuNDk5Ii8+DQo8L2c+DQo8ZWxsaXBzZSB0cmFuc2Zvcm09Im1hdHJpeCgtMC4yNTUzIDAuOTY2OSAtMC45NjY5IC0wLjI1NTMgNjUzLjgyNDIgOTcuNjgyOSkiIHN0eWxlPSJmaWxsOiNBNTkwNkY7IiBjeD0iMjg5LjI5MyIgY3k9IjMwMC42MzkiIHJ4PSIxMi43IiByeT0iMTIiLz4NCjxwYXRoIHN0eWxlPSJmaWxsOiMyOTI5Mjk7IiBkPSJNMzUzLjUsMjY4LjJIMzQxYzAsMC0yLjEtMi43LTIuMy02LjJjLTAuMy0zLjYsMi4zLTUuNiwyLjMtNS42aDEyLjVWMjY4LjJ6Ii8+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8L3N2Zz4NCg==
    mediatype: image/svg+xml
  install:
    spec:
      deployments:
      - name: gramola-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: gramola-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: gramola-operator
            spec:
              containers:
              - command:
                - gramola-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: gramola-operator
                image: quay.io/cvicensa/gramola-operator-image:0.0.1
                imagePullPolicy: Always
                name: gramola-operator
                resources: {}
              serviceAccountName: gramola-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - pods/exec
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - gramola-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - gramola.redhat.com
          resources:
          - '*'
          - appservices
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        serviceAccountName: gramola-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - gramola
  - backend
  maintainers:
  - email: admin@gramola.com
    name: Gramola Inc.
  maturity: alpha
  provider:
    name: Gramola Inc.
  replaces: gramola-operator.v0.0.0
  version: 0.0.1
